settings:
  snapmaker_components:
    label: Snapmaker Components
    items:
      rfid:
        label: Filament Detection
        help_url: https://snapmakeru1-extended-firmware.pages.dev/rfid_support#alternative-detection-systems
        description: Set how filament is detected.
        get_cmd:
          - /usr/local/bin/extended-config.py
          - get
          - /oem/printer_data/config/extended/extended2.cfg
          - components
          - rfid
          - snapmaker
        options:
          external:
            label: External
            cmd:
              - bash
              - -xc
              - |
                /usr/local/bin/extended-config.py add /oem/printer_data/config/extended/extended2.cfg components rfid external
                /etc/init.d/S99openrfid stop
                /etc/init.d/S59rfid-support restart
                /etc/init.d/S60klipper restart
          snapmaker:
            label: Snapmaker
            cmd:
              - bash
              - -xc
              - |
                /usr/local/bin/extended-config.py add /oem/printer_data/config/extended/extended2.cfg components rfid snapmaker
                /etc/init.d/S99openrfid stop
                /etc/init.d/S59rfid-support restart
                /etc/init.d/S60klipper restart
        default: snapmaker
