#!/bin/sh

EXTENDED_CFG="/home/lava/printer_data/config/extended/extended2.cfg"
SITES_ENABLED="/etc/nginx/sites-enabled"
SITES_AVAILABLE="/etc/nginx/sites-available"

configure_nginx_site()
{
	rm -f "$SITES_ENABLED/fluidd"
	rm -f "$SITES_ENABLED/mainsail"

	WEB_FRONTEND=$(/usr/local/bin/extended-config.py get "$EXTENDED_CFG" web frontend fluidd)

	if [ "$WEB_FRONTEND" = "mainsail" ]; then
		echo "Enabling Mainsail web interface"
		ln -sf "$SITES_AVAILABLE/mainsail" "$SITES_ENABLED/"
	else
		echo "Enabling Fluidd web interface"
		ln -sf "$SITES_AVAILABLE/fluidd" "$SITES_ENABLED/"
	fi
}

case "$1" in
	start)
		configure_nginx_site
		;;

	stop)
		;;

	restart|reload)
		configure_nginx_site
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac

exit $?
